### ISSUE TITLE
Cpu input boost issue 

### ISSUE THREAD

**Issue by JohnFawkes** [Magisk-Modules-Repo/legendary_kernel_tweaks#1]
This is the issue I've been having. Stock oreo lg v30. The log says cpu input boost and cpu boost isn't supported. 

This is what the dev of my custom kernel said about it, 
yeah sure, it doesn't have drivers/cpufreq/cpu-boost.c compiled in, it instead uses drivers/devfreq/devfreq_boost.c & drivers/cpufreq/cpu_input_boost.c (kerneltoast/sultanxda implementation)

So if you could add support for this that would be great thanks

**Comment by korom42** [comment]
Support for sultanxda cpu boost implementation added
https://github.com/Magisk-Modules-Repo/legendary_kernel_tweaks/commit/fe61c58516fb568e8cab0b2f6ab96b0337cbdd37

**Comment by JohnFawkes** [comment]
Thanks
